[package]
name = "gba"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/RepeatedRoot/gba"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
bitpat = "0.1.1"